<?php

use App\Controllers\Category;
use App\Controllers\Dashboard;
use App\Controllers\HomeController;
use App\Controllers\LoginController;
use App\Controllers\SignupController;
use App\Controllers\TagController;
use App\Controllers\TestController;
use App\Controllers\UserController;
use App\Controllers\WikiController;
use App\Router;

$router = new Router();

$router->get('/', HomeController::class, 'index');
$router->get('/dashboard', Dashboard::class, 'index');
$router->get('/category', Category::class, 'category');
$router->get('/categoryadd', Category::class, 'categoryadd');
$router->post('/categoryadd', Category::class, 'categoryadd');
$router->get('/categoryupdate', Category::class, 'updateform');
$router->post('/categoryupdate', Category::class, 'categoryupdate');
$router->get('/categorydelete', Category::class, 'categorydelete');
$router->get('/user', UserController::class, 'show');
$router->get('/userdelete', UserController::class, 'userdelete');
$router->get('/logout', UserController::class, 'logout');
$router->post('/insert', HomeController::class, 'insert');
$router->get('/tag', TagController::class, 'tag');
$router->get('/tagadd', TagController::class, 'tagadd');
$router->post('/tagadd', TagController::class, 'tagadd');
$router->post('/tagupdate', TagController::class, 'tagupdate');
$router->get('/tagupdate', TagController::class, 'tagupdate');
$router->post('/tgaupdate', TagController::class, 'tagupdate');
$router->get('/tagupdate', TagController::class, 'updateform');
$router->post('/tagupdate', TagController::class, 'updateform');
$router->get('/tagdelete', TagController::class, 'tagdelete');
$router->get('/wiki', WikiController::class, 'wiki');
$router->get('/wikifr', WikiController::class, 'wikifr');
$router->get('/wikifradd', WikiController::class, 'wikifrshow');
$router->post('/wikifradd', WikiController::class, 'wikifradd');
$router->get('/wikifrupdate', WikiController::class, 'wikifrupdateshow');
$router->post('/wikifradd', WikiController::class, 'wikifradd');
$router->post('/wikifrupdate', WikiController::class, 'wikifrupdateshow');
$router->post('/wikifrupdate', WikiController::class, 'wikifrupdate');
$router->get('/wikiadd', WikiController::class, 'wikiadd');
$router->post('/wikiadd', WikiController::class, 'wikiadd');
$router->get('/login', LoginController::class, 'show');
$router->post('/login', LoginController::class, 'Userlogin');
// $router->get('/login', LoginController::class, 'Userlogin');
$router->get('/signup', SignupController::class, 'show');
// $router->get('/signup', SignupController::class, 'useradd');
$router->post('/signup', SignupController::class, 'useradd');
$router->get('/test', TestController::class, 'add');
$router->dispatch();
